//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.ECM.eCase.SusDeb.DOI.Search.SaveSearchCriteriaWebPart {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint.WebControls;
    using System.Web.Security;
    using Microsoft.SharePoint.Utilities;
    using System.Web.UI;
    using System;
    using System.Web.UI.WebControls;
    using System.Collections.Specialized;
    using Microsoft.SharePoint;
    using System.Collections;
    using System.Web.Profile;
    using System.Text;
    using System.Web.Caching;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.SessionState;
    using System.Web.UI.HtmlControls;
    
    
    public partial class SaveSearchCriteriaWebPart {
        
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnSearchUrl;
        
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnSearchKeywords;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlSavedSearches;
        
        protected global::System.Web.UI.WebControls.LinkButton btnRunSearch;
        
        public static implicit operator global::System.Web.UI.TemplateControl(SaveSearchCriteriaWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhdnSearchUrl() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hdnSearchUrl = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hdnSearchUrl";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhdnSearchKeywords() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hdnSearchKeywords = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hdnSearchKeywords";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlSavedSearches() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlSavedSearches = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlSavedSearches";
            @__ctrl.CssClass = "saved-searches-select";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlbtnRunSearch() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.btnRunSearch = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnRunSearch";
            @__ctrl.CssClass = "ecase-search-link";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<i class=\"icon-play\"></i> Run Search"));
            @__ctrl.Click -= new System.EventHandler(this.btnRunSearch_Click);
            @__ctrl.Click += new System.EventHandler(this.btnRunSearch_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Treasury.ECM.eCase.SusDeb.DOI.Search.SaveSearchCriteriaWebPart.SaveSearchCriteriaWebPart @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl1;
            @__ctrl1 = this.@__BuildControlhdnSearchUrl();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl2;
            @__ctrl2 = this.@__BuildControlhdnSearchKeywords();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControlddlSavedSearches();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.LinkButton @__ctrl4;
            @__ctrl4 = this.@__BuildControlbtnRunSearch();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n\r\n<a id=\"btnSaveQuery\" class=\"ecase-search-link\" onclick=\"OpenModal()\"><i class" +
                    "=\"icon-save\"></i> Save Search Query</a>&nbsp;");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("&nbsp");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    function OpenModal() {\r\n        var se" +
                    "archUrl = document.getElementById(\"");
                                         @__w.Write( hdnSearchUrl.ClientID );

            @__w.Write(@""").value;
        var options = SP.UI.$create_DialogOptions();
        options.url = ""../../_layouts/eCaseSearch/SaveSearchQuery.aspx?searchUrl="" + searchUrl;
        options.width = 800;
        options.height = 600;
        options.showMaximize = false;
        options.allowMaximize = false;
        options.dialogReturnValueCallback = Function.createDelegate(null, sitePropertiesDialogCallback);
        SP.UI.ModalDialog.showModalDialog(options);
    }

    function sitePropertiesDialogCallback(dialogResult, returnValue) {
        document.location.reload(true);
    }

</script>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
